stages: # Diffrents job a executer dans l'ordre
  - build
  - test
  - sonarqube-check


sonarqube-check:
  stage: sonarqube-check
  image: 
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - main



# Job pour construire le frontend Vue.js
build-frontend: 
  stage: build
  script:
    - cd lomebordesfront/frontend
    - npm install
    - npm run build

# Job pour construire le backend Spring Boot
build-backend:
  stage: build
  script:
    - echo "Current directory: $PWD"
    - cd lomebordes/backend
    - mvn clean package



# Job pour tester le frontend Vue.js
# test-frontend:
#   stage: test
#   script:
#     - cd lomebordesfront/frontend
#     - npm run test -- --coverage

# Job pour tester le backend Spring Boot
test-backend:
  stage: test
  script:
    - cd lomebordes/backend
    - mvn test
