# version: '3.5'

services:
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql