
services:
  backend:
    build:
      context: ./lomebordes
      dockerfile: dockerfile.back
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3312/crazymo
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./lomebordesfront
      dockerfile: dockerfile
    container_name: frontend
    ports:
      - '5173:80'
    networks:
      - app-network
    depends_on:
      - backend

  db:
    build:
      context: ./lomebordes
      dockerfile: dockerfile
    container_name: mariadb
    ports:
      - '3312:3312'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: